spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/DisasterManagementPlatform?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: DMProot2024
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 10001
